export const getAlbumsCount = async () => {
  return {
    status: "0",
    DataCount: 47,
    timestamp: "2024-08-12 13:38:59",
  };
};

export const getAlbumsList = async () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve([
        {
          FileItem: {
            iPhotoAlbumId: "s7iy2e",
            cAlbumTitle: "01",
            iFaceCover: "r08wnq",
            FaceId: "var3kn",
            PhotoCount: "44",
            VideoCount: 6,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#08562b",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "k80fsa",
            cAlbumTitle: "02",
            iFaceCover: "1jsjnw",
            FaceId: "0x3jhd",
            PhotoCount: "76",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#6f1089",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "t7sgmq",
            cAlbumTitle: "03",
            iFaceCover: "myc12u",
            FaceId: "dok904",
            PhotoCount: "73",
            VideoCount: 9,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#d26856",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "vzkzgk",
            cAlbumTitle: "04",
            iFaceCover: "u66hhb",
            FaceId: "my60y7",
            PhotoCount: "9",
            VideoCount: 8,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#35100b",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "r6u00q",
            cAlbumTitle: "05",
            iFaceCover: "8lg7ae",
            FaceId: "135y1m",
            PhotoCount: "10",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#49c19b",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "3wdazk",
            cAlbumTitle: "06",
            iFaceCover: "6zs9ip",
            FaceId: "equ4zp",
            PhotoCount: "18",
            VideoCount: 0,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#ea6284",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "opu95y",
            cAlbumTitle: "07",
            iFaceCover: "8z7ny0",
            FaceId: "m917wk",
            PhotoCount: "40",
            VideoCount: 0,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#6ff037",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "hessmv",
            cAlbumTitle: "08",
            iFaceCover: "p85h03",
            FaceId: "450slh",
            PhotoCount: "52",
            VideoCount: 1,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#353e88",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "4kfyta",
            cAlbumTitle: "09",
            iFaceCover: "3c0m1b",
            FaceId: "xo5dy0",
            PhotoCount: "60",
            VideoCount: 9,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#82bff7",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "g40btk",
            cAlbumTitle: "10",
            iFaceCover: "jtsf2a",
            FaceId: "oghn3o",
            PhotoCount: "49",
            VideoCount: 9,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#b903fb",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "7r33mj",
            cAlbumTitle: "11",
            iFaceCover: "pj4od4",
            FaceId: "46n5q2",
            PhotoCount: "80",
            VideoCount: 8,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#70c6fc",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "cjw4by",
            cAlbumTitle: "12",
            iFaceCover: "hroipi",
            FaceId: "wsg3gc",
            PhotoCount: "20",
            VideoCount: 1,
            LastUpdate: "2024-08-12T08:27:18.989Z",
            background: "#ed434e",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "e747n2",
            cAlbumTitle: "13",
            iFaceCover: "fc7l5s",
            FaceId: "7mifpm",
            PhotoCount: "15",
            VideoCount: 2,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#af9fc0",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "rlzb5l",
            cAlbumTitle: "14",
            iFaceCover: "2iayan",
            FaceId: "udjo2t",
            PhotoCount: "45",
            VideoCount: 9,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#266b9d",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "lj30to",
            cAlbumTitle: "15",
            iFaceCover: "kewgv2",
            FaceId: "orpfkr",
            PhotoCount: "19",
            VideoCount: 8,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#d19edb",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "owljoq",
            cAlbumTitle: "16",
            iFaceCover: "0hp85g",
            FaceId: "ff1lar",
            PhotoCount: "0",
            VideoCount: 7,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#8225b9",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "otnnzu",
            cAlbumTitle: "17",
            iFaceCover: "uo3thg",
            FaceId: "586fq8",
            PhotoCount: "86",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#b7e873",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "8iamab",
            cAlbumTitle: "18",
            iFaceCover: "xyok4i",
            FaceId: "zb3xgi",
            PhotoCount: "67",
            VideoCount: 0,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#86ee1f",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "8108zk",
            cAlbumTitle: "19",
            iFaceCover: "yke0m7",
            FaceId: "j66viw",
            PhotoCount: "78",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#15fa29",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "vznam8",
            cAlbumTitle: "20",
            iFaceCover: "gvaizx",
            FaceId: "4mg3fw",
            PhotoCount: "17",
            VideoCount: 5,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#86dd51",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "wzulpj",
            cAlbumTitle: "21",
            iFaceCover: "upqlmr",
            FaceId: "d4m5ir",
            PhotoCount: "36",
            VideoCount: 9,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#1cdf99",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "hl8ax7",
            cAlbumTitle: "22",
            iFaceCover: "334dx5",
            FaceId: "w84u41",
            PhotoCount: "30",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#720378",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "tbayrc",
            cAlbumTitle: "23",
            iFaceCover: "25cee3",
            FaceId: "t91wot",
            PhotoCount: "14",
            VideoCount: 8,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#eeb531",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "o4p1x6",
            cAlbumTitle: "24",
            iFaceCover: "4nhvpo",
            FaceId: "nmnig8",
            PhotoCount: "49",
            VideoCount: 7,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#44e29b",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "znm0e0",
            cAlbumTitle: "25",
            iFaceCover: "5raibg",
            FaceId: "148ysp",
            PhotoCount: "55",
            VideoCount: 1,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#03b5a1",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "0bvcz4",
            cAlbumTitle: "26",
            iFaceCover: "8op0x7",
            FaceId: "z1ptud",
            PhotoCount: "14",
            VideoCount: 2,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#f9041a",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "cm12uk",
            cAlbumTitle: "27",
            iFaceCover: "rw7qki",
            FaceId: "bayff6",
            PhotoCount: "82",
            VideoCount: 8,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#d147f4",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "4x15sq",
            cAlbumTitle: "28",
            iFaceCover: "wzp1wp",
            FaceId: "hnil3e",
            PhotoCount: "3",
            VideoCount: 4,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#00cace",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "p4n3p3",
            cAlbumTitle: "29",
            iFaceCover: "8r4iqj",
            FaceId: "kglr4y",
            PhotoCount: "63",
            VideoCount: 2,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#e7d57f",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "y9gh92",
            cAlbumTitle: "30",
            iFaceCover: "e2tz50",
            FaceId: "gn9r5b",
            PhotoCount: "72",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#83e362",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "klh5am",
            cAlbumTitle: "31",
            iFaceCover: "czl6jq",
            FaceId: "2h7lz6",
            PhotoCount: "43",
            VideoCount: 1,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#3dba40",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "fdurvq",
            cAlbumTitle: "32",
            iFaceCover: "tlux3j",
            FaceId: "5rgjyu",
            PhotoCount: "69",
            VideoCount: 0,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#259f7b",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "n91vg9",
            cAlbumTitle: "33",
            iFaceCover: "kldnb5",
            FaceId: "40t3ay",
            PhotoCount: "8",
            VideoCount: 7,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#aa0c96",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "0du8ig",
            cAlbumTitle: "34",
            iFaceCover: "ji0drx",
            FaceId: "7grn7o",
            PhotoCount: "92",
            VideoCount: 2,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#f866d7",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "hms5n2",
            cAlbumTitle: "35",
            iFaceCover: "p1jfnd",
            FaceId: "tk1urz",
            PhotoCount: "59",
            VideoCount: 4,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#8237b8",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "es1f01",
            cAlbumTitle: "36",
            iFaceCover: "2pdrjg",
            FaceId: "nhlutj",
            PhotoCount: "41",
            VideoCount: 4,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#7b4136",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "2qkb35",
            cAlbumTitle: "37",
            iFaceCover: "7rge5u",
            FaceId: "1r00x6",
            PhotoCount: "26",
            VideoCount: 8,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#b0340f",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "x9pfgr",
            cAlbumTitle: "38",
            iFaceCover: "my1vnw",
            FaceId: "68k1io",
            PhotoCount: "78",
            VideoCount: 3,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#48c4b3",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "arsv53",
            cAlbumTitle: "39",
            iFaceCover: "1je4za",
            FaceId: "s1eylb",
            PhotoCount: "17",
            VideoCount: 0,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#4dbf64",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "aono2t",
            cAlbumTitle: "40",
            iFaceCover: "o815t2",
            FaceId: "psaysi",
            PhotoCount: "21",
            VideoCount: 1,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#5644fa",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "x0bdpe",
            cAlbumTitle: "41",
            iFaceCover: "57s79u",
            FaceId: "s7jumb",
            PhotoCount: "58",
            VideoCount: 5,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#c635d2",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "5pp4k6",
            cAlbumTitle: "42",
            iFaceCover: "4rqy0f",
            FaceId: "4njebs",
            PhotoCount: "23",
            VideoCount: 6,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#ffb42d",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "oclbj2",
            cAlbumTitle: "43",
            iFaceCover: "kk6v3w",
            FaceId: "xlaeey",
            PhotoCount: "13",
            VideoCount: 0,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#9240fc",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "vmwyhc",
            cAlbumTitle: "44",
            iFaceCover: "3be802",
            FaceId: "r2q40z",
            PhotoCount: "80",
            VideoCount: 1,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#d98499",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "wn5ul2",
            cAlbumTitle: "45",
            iFaceCover: "1fvi2n",
            FaceId: "08sj8a",
            PhotoCount: "83",
            VideoCount: 5,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#0161c8",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "cnqycb",
            cAlbumTitle: "46",
            iFaceCover: "fibeck",
            FaceId: "9cw4c5",
            PhotoCount: "61",
            VideoCount: 6,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#e47108",
          },
        },
        {
          FileItem: {
            iPhotoAlbumId: "awptad",
            cAlbumTitle: "47",
            iFaceCover: "nt2t0k",
            FaceId: "3woh8g",
            PhotoCount: "98",
            VideoCount: 4,
            LastUpdate: "2024-08-12T08:27:18.990Z",
            background: "#161e72",
          },
        },
      ]);
    }, 2000);
  });
};
